-- chizuData.ts + demoUsers.ts 기준 데모 시드
-- image-marketplace-flow.sql 실행 후 이 파일을 실행하세요.
-- ON CONFLICT로 여러 번 실행해도 안전합니다.

insert into public.marketplace_demo_users (id, display_name, handle, avatar_url)
values
  ('min', 'Min Park', 'minarchive', '/images/chizu/profile_default_180x180_00.png'),
  ('haru', 'Haru Studio', 'harustudio', '/images/chizu/profile_default_180x180_01.png'),
  ('noah', 'Noah Kim', 'noahdraws', '/images/chizu/profile_default_180x180_00.png'),
  ('yuna', 'Yuna Lee', 'yunalee', '/images/chizu/profile_default_180x180_01.png'),
  ('collector-a', 'Jin Collector', 'jincollects', '/images/chizu/profile_default_180x180_01.png'),
  ('collector-b', 'Sora Buyer', 'sorabuyer', '/images/chizu/profile_default_180x180_00.png'),
  ('guest', 'Guest User', 'guest', '/images/chizu/profile_default_180x180_00.png')
on conflict (id) do update set
  display_name = excluded.display_name,
  handle = excluded.handle,
  avatar_url = excluded.avatar_url;

insert into public.marketplace_demo_works (
  id,
  title,
  description,
  image_url,
  width,
  height,
  creator_id,
  owner_id,
  ownership_status,
  listing_status,
  asking_price,
  last_sale_price,
  offer_count,
  tags,
  usage_rights
)
values
  (
    'work-01',
    'Archive Bloom',
    '',
    '/images/chizu/main1.jpg',
    1000,
    703,
    'min',
    'min',
    'OWNED_BY_CREATOR',
    'LISTED',
    280000,
    null,
    0,
    array['illustration', 'character'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-02',
    'Blue Signal',
    '',
    '/images/chizu/main2.jpg',
    778,
    1100,
    'haru',
    'collector-a',
    'OWNED_BY_COLLECTOR',
    'OFFER_OPEN',
    null,
    160000,
    3,
    array['anime', 'blue'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-03',
    'Soft Protocol',
    '',
    '/images/chizu/main3.jpg',
    700,
    811,
    'noah',
    'collector-a',
    'OWNED_BY_COLLECTOR',
    'OFFER_OPEN',
    null,
    420000,
    5,
    array['portrait', 'license'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":false},{"label":"재판매 가능","enabled":true}]'::jsonb
  ),
  (
    'work-04',
    'Creator Room',
    '',
    '/images/chizu/main4.jpg',
    1000,
    707,
    'yuna',
    'yuna',
    'OWNED_BY_CREATOR',
    'LISTED',
    310000,
    null,
    1,
    array['3d', 'interior'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-05',
    'Layered Dream',
    '',
    '/images/chizu/main5.jpg',
    782,
    1100,
    'min',
    'collector-b',
    'OWNED_BY_COLLECTOR',
    'OFFER_OPEN',
    null,
    190000,
    2,
    array['concept', 'dream'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-06',
    'Neon Field',
    '',
    '/images/chizu/main6.jpg',
    1000,
    707,
    'haru',
    'haru',
    'OWNED_BY_CREATOR',
    'LISTED',
    350000,
    null,
    0,
    array['neon', 'landscape'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-07',
    'Silent Light',
    '',
    '/images/chizu/main7.jpg',
    1000,
    683,
    'noah',
    'collector-a',
    'OWNED_BY_COLLECTOR',
    'OFFER_OPEN',
    null,
    220000,
    4,
    array['archive', 'quiet'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-08',
    'Pixel Memory',
    '',
    '/images/chizu/main8.png',
    2963,
    1667,
    'yuna',
    'yuna',
    'OWNED_BY_CREATOR',
    'LISTED',
    130000,
    null,
    0,
    array['pixel', 'memory'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":false}]'::jsonb
  ),
  (
    'work-09',
    'Open Canvas',
    '',
    '/images/chizu/main9.png',
    2963,
    1667,
    'min',
    'collector-b',
    'OWNED_BY_COLLECTOR',
    'OFFER_OPEN',
    null,
    480000,
    7,
    array['canvas', 'exclusive'],
    '[{"label":"상업적 이용 가능","enabled":true},{"label":"독점 사용권 이전","enabled":true},{"label":"2차 수정 가능","enabled":true},{"label":"재판매 가능","enabled":true}]'::jsonb
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  image_url = excluded.image_url,
  width = excluded.width,
  height = excluded.height,
  creator_id = excluded.creator_id,
  owner_id = excluded.owner_id,
  ownership_status = excluded.ownership_status,
  listing_status = excluded.listing_status,
  asking_price = excluded.asking_price,
  last_sale_price = excluded.last_sale_price,
  offer_count = excluded.offer_count,
  tags = excluded.tags,
  usage_rights = excluded.usage_rights,
  updated_at = now();
