import { marketplaceUsers } from "@/lib/image-marketplace-flow/demoUsers";
import type {
  ListingStatus,
  MarketplaceUser,
  UsageRight,
  WorkOwnershipStatus,
} from "@/lib/image-marketplace-flow/marketplaceTypes";

export type WorkItem = {
  id: string;
  title: string;
  artist: string;
  image: string;
  price: number;
  width: number;
  height: number;
  tags: string[];
  status: "Buy now" | "Auction" | "Offer";
  creator: MarketplaceUser;
  owner: MarketplaceUser;
  ownershipStatus: WorkOwnershipStatus;
  listingStatus: ListingStatus;
  askingPrice: number | null;
  lastSalePrice: number | null;
  offerCount: number;
  usageRights: UsageRight[];
};

const defaultRights: UsageRight[] = [
  { label: "상업적 이용 가능", enabled: true },
  { label: "독점 사용권 이전", enabled: true },
  { label: "2차 수정 가능", enabled: true },
  { label: "재판매 가능", enabled: false },
];

export const works: WorkItem[] = [
  {
    id: "work-01",
    title: "Archive Bloom",
    artist: "Min Park",
    image: "/images/chizu/main1.jpg",
    price: 280_000,
    width: 1000,
    height: 703,
    tags: ["illustration", "character"],
    status: "Buy now",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.min,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 280_000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-02",
    title: "Blue Signal",
    artist: "Haru Studio",
    image: "/images/chizu/main2.jpg",
    price: 160_000,
    width: 778,
    height: 1100,
    tags: ["anime", "blue"],
    status: "Offer",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 160_000,
    offerCount: 3,
    usageRights: defaultRights,
  },
  {
    id: "work-03",
    title: "Soft Protocol",
    artist: "Noah Kim",
    image: "/images/chizu/main3.jpg",
    price: 420_000,
    width: 700,
    height: 811,
    tags: ["portrait", "license"],
    status: "Offer",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 420_000,
    offerCount: 5,
    usageRights: [
      { label: "상업적 이용 가능", enabled: true },
      { label: "독점 사용권 이전", enabled: true },
      { label: "2차 수정 가능", enabled: false },
      { label: "재판매 가능", enabled: true },
    ],
  },
  {
    id: "work-04",
    title: "Creator Room",
    artist: "Yuna Lee",
    image: "/images/chizu/main4.jpg",
    price: 310_000,
    width: 1000,
    height: 707,
    tags: ["3d", "interior"],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 310_000,
    lastSalePrice: null,
    offerCount: 1,
    usageRights: defaultRights,
  },
  {
    id: "work-05",
    title: "Layered Dream",
    artist: "Studio Oji",
    image: "/images/chizu/main5.jpg",
    price: 190_000,
    width: 782,
    height: 1100,
    tags: ["concept", "dream"],
    status: "Offer",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 190_000,
    offerCount: 2,
    usageRights: defaultRights,
  },
  {
    id: "work-06",
    title: "Neon Field",
    artist: "Kira",
    image: "/images/chizu/main6.jpg",
    price: 350_000,
    width: 1000,
    height: 707,
    tags: ["neon", "landscape"],
    status: "Buy now",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.haru,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 350_000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-07",
    title: "Silent Light",
    artist: "Jun Seo",
    image: "/images/chizu/main7.jpg",
    price: 220_000,
    width: 1000,
    height: 683,
    tags: ["archive", "quiet"],
    status: "Offer",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 220_000,
    offerCount: 4,
    usageRights: defaultRights,
  },
  {
    id: "work-08",
    title: "Pixel Memory",
    artist: "Mori",
    image: "/images/chizu/main8.png",
    price: 130_000,
    width: 2963,
    height: 1667,
    tags: ["pixel", "memory"],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 130_000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-09",
    title: "Open Canvas",
    artist: "Sora",
    image: "/images/chizu/main9.png",
    price: 480_000,
    width: 2963,
    height: 1667,
    tags: ["canvas", "exclusive"],
    status: "Offer",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 480_000,
    offerCount: 7,
    usageRights: [
      { label: "상업적 이용 가능", enabled: true },
      { label: "독점 사용권 이전", enabled: true },
      { label: "2차 수정 가능", enabled: true },
      { label: "재판매 가능", enabled: true },
    ],
  },
];
