import { marketplaceUsers } from "@/lib/image-marketplace-flow/demoUsers";
import type {
  ListingStatus,
  MarketplaceUser,
  UsageRight,
  WorkOwnershipStatus,
} from "@/lib/image-marketplace-flow/marketplaceTypes";

export type WorkItem = {
  id: string;
  title: string;
  artist: string;
  image: string;
  price: number;
  width: number;
  height: number;
  tags: string[];
  status: "Buy now" | "Auction" | "Offer";
  creator: MarketplaceUser;
  owner: MarketplaceUser;
  ownershipStatus: WorkOwnershipStatus;
  listingStatus: ListingStatus;
  askingPrice: number | null;
  lastSalePrice: number | null;
  offerCount: number;
  usageRights: UsageRight[];
};

const defaultRights: UsageRight[] = [
  { label: "상업적 이용 가능", enabled: true },
  { label: "독점 사용권 이전", enabled: true },
  { label: "2차 수정 가능", enabled: true },
  { label: "재판매 가능", enabled: false },
];

export const works: WorkItem[] = [
  {
    id: "work-01",
    title: "Square Light Portrait",
    artist: "Min Park",
    image: "/images/marketplace/mock/andsproject-girl-8435329_1920.png",
    price: 320000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.min,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 320000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-02",
    title: "Twin Bear Guards",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/betidraws-bears-8421343_1920.jpg",
    price: 285000,
    width: 1600,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.haru,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 285000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-03",
    title: "Neon Alley Runner",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/andsproject-anime-9717013_1920.jpg",
    price: 410000,
    width: 1920,
    height: 1080,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 410000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-04",
    title: "Harbor Crab Study",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/alan_frijns-crab-7627632_1920.jpg",
    price: 195000,
    width: 1920,
    height: 1280,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.noah,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 195000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-05",
    title: "Pumpkin Market Night",
    artist: "Min Park",
    image: "/images/marketplace/mock/betidraws-halloween-8273648_1920.jpg",
    price: 240000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.min,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 240000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-06",
    title: "Koi Pond Silence",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/saydung-fish-5876892_1920.jpg",
    price: 275000,
    width: 1536,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.haru,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 275000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-07",
    title: "Watercolor Coast",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/lextotan-watercolor-3147007_1920.jpg",
    price: 360000,
    width: 1920,
    height: 890,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 360000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-08",
    title: "Morning Ridge Line",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/impermanent-mountains-7852446_1920.jpg",
    price: 298000,
    width: 1080,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.noah,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 298000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-09",
    title: "Monstera Window",
    artist: "Min Park",
    image: "/images/marketplace/mock/biancavandijk-monstera-7225064_1920.jpg",
    price: 210000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.min,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 210000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-10",
    title: "Ink Garden Sketch",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/mymyberries-drawing-10057403_1920.jpg",
    price: 265000,
    width: 1357,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.haru,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 265000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-11",
    title: "Midnight Studio Glow",
    artist: "Min Park",
    image: "/images/marketplace/mock/andsproject-girl-8435340_1920.png",
    price: 180000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 180000,
    offerCount: 2,
    usageRights: defaultRights,
  },
  {
    id: "work-12",
    title: "Forest Deer at Dusk",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/alan_frijns-deer-7627666_1920.jpg",
    price: 220000,
    width: 1920,
    height: 1562,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 220000,
    offerCount: 3,
    usageRights: defaultRights,
  },
  {
    id: "work-13",
    title: "Raincoat Commute",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/andsproject-girl-9548776_1920.jpg",
    price: 340000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 340000,
    offerCount: 1,
    usageRights: defaultRights,
  },
  {
    id: "work-14",
    title: "Vintage Stage Silhouette",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/arttower-charlie-chaplin-6665659_1920.jpg",
    price: 155000,
    width: 1440,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 155000,
    offerCount: 4,
    usageRights: defaultRights,
  },
  {
    id: "work-15",
    title: "Subway Platform Pause",
    artist: "Min Park",
    image: "/images/marketplace/mock/tiemcuala12-woman-9461840_1920.jpg",
    price: 190000,
    width: 1536,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 190000,
    offerCount: 2,
    usageRights: defaultRights,
  },
  {
    id: "work-16",
    title: "Candle Alley Walk",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/betidraws-halloween-9086123_1920.jpg",
    price: 250000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 250000,
    offerCount: 5,
    usageRights: defaultRights,
  },
  {
    id: "work-17",
    title: "Fox in Amber Woods",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/mymyberries-fox-9106452_1920.jpg",
    price: 315000,
    width: 1357,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.noah,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 315000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-18",
    title: "Hearts in Motion",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/ninikvaratskhelia-love-7436367_1920.jpg",
    price: 388000,
    width: 1358,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 388000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-19",
    title: "Velvet Coat Portrait",
    artist: "Min Park",
    image: "/images/marketplace/mock/pheladii-girl-8788687_1920.jpg",
    price: 425000,
    width: 1707,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.min,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 425000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-20",
    title: "Creative Burst",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/cdd20-creativity-4912473_1920.jpg",
    price: 178000,
    width: 1080,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.haru,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 178000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-21",
    title: "Contest Day Banner",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/biancavandijk-japan-contest-9083822_1920.jpg",
    price: 205000,
    width: 1920,
    height: 1344,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 205000,
    offerCount: 2,
    usageRights: defaultRights,
  },
  {
    id: "work-22",
    title: "Felt Tip Cityscape",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/svetlanakv-felt-tip-pen-drawing-1019132_1920.jpg",
    price: 168000,
    width: 1272,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 168000,
    offerCount: 3,
    usageRights: defaultRights,
  },
  {
    id: "work-23",
    title: "Late Café Reader",
    artist: "Min Park",
    image: "/images/marketplace/mock/tiemcuala12-woman-9461838_1920.jpg",
    price: 142000,
    width: 1536,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.min,
    owner: marketplaceUsers.collectorA,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 142000,
    offerCount: 1,
    usageRights: defaultRights,
  },
  {
    id: "work-24",
    title: "Umbrella Crossing",
    artist: "Haru Studio",
    image: "/images/marketplace/mock/tiemcuala12-woman-9488137_1920.jpg",
    price: 228000,
    width: 1536,
    height: 1920,
    tags: [],
    status: "Offer",
    creator: marketplaceUsers.haru,
    owner: marketplaceUsers.collectorB,
    ownershipStatus: "OWNED_BY_COLLECTOR",
    listingStatus: "OFFER_OPEN",
    askingPrice: null,
    lastSalePrice: 228000,
    offerCount: 4,
    usageRights: defaultRights,
  },
  {
    id: "work-25",
    title: "Autumn Berry Still Life",
    artist: "Yuna Lee",
    image: "/images/marketplace/mock/mymyberries-autumn-9079361_1920.jpg",
    price: 302000,
    width: 1357,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.yuna,
    owner: marketplaceUsers.yuna,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 302000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  },
  {
    id: "work-26",
    title: "City Window Reflection",
    artist: "Noah Kim",
    image: "/images/marketplace/mock/andsproject-girl-9239059_1920.jpg",
    price: 395000,
    width: 1920,
    height: 1920,
    tags: [],
    status: "Buy now",
    creator: marketplaceUsers.noah,
    owner: marketplaceUsers.noah,
    ownershipStatus: "OWNED_BY_CREATOR",
    listingStatus: "LISTED",
    askingPrice: 395000,
    lastSalePrice: null,
    offerCount: 0,
    usageRights: defaultRights,
  }
];
